### ISSUE TITLE
 SSL peer certificate or SSH remote key was not OK

### ISSUE THREAD

**Issue by lexcorp** [w-henderson/Kascreech#5]
cargo run
error: failed to download from `https://crates.io/api/v1/crates/actix-codec/0.3.0/download`

Caused by:
  [60] SSL peer certificate or SSH remote key was not OK (SSL certificate problem: unable to get local issuer certificate)

**Comment by w-henderson** [comment]
This looks like an issue with your Rust installation or network configuration rather than with Kascreech... You need Rust Nightly to run the server but that wouldn't cause this specific issue. It could be a problem with your local mirror of crates.io or possibly an SSL misconfiguration on your part? Try resetting network settings or connecting to a different network is what I would suggest.

**Comment by lexcorp** [comment]
@w-henderson Hello, thank you for your answer, I can tell you that I already managed to solve this detail, the problem was related to the configuration of the firewall in my office, after configuring the access permissions in the firewall I could continue the installation.

"You need Rust Nightly to run the server"       **how do I do this?**

**Comment by w-henderson** [comment]
Please see Issue #6.

**Comment by lexcorp** [comment]
Thanks @w-henderson after After applying the changes you suggested, it worked...

![image](https://user-images.githubusercontent.com/5751288/118529805-86dab180-b709-11eb-8200-158fddb93d39.png)

**Comment by w-henderson** [comment]
This looks like your machine already has something bound to port 8080 - you could change the port in the code or stop whatever's already running on that port.
